var gulp = require('gulp');
var gutil = require('gulp-util');
var config = require('../../config')
  .iconFont;
var swig = require('gulp-swig');
var rename = require('gulp-rename');
var handleErrors = require('../../util/handleErrors');

module.exports = function(glyphs, options) {
  return gulp.src(config.template)
    .pipe(swig({
      data: {
        icons: glyphs.map(function(glyph) {
          gutil.log(gutil.colors.green('+ adding ' + glyph.name + ' glyph'));
          return {
            name: glyph.name,
            code: glyph.unicode[0].charCodeAt(0).toString(16).toUpperCase(),
          };
        }),

        fontName: config.options.fontName,
        fontPath: config.fontPath,
        className: config.className,
        comment: 'DO NOT EDIT DIRECTLY!'
               + '\n Generated by gulp/tasks/iconFont/index.js'
               + '\n from ' + config.template,
      },
    }))
    .on('error', handleErrors)
    .pipe(rename(config.lessOutputName))
    .pipe(gulp.dest(config.lessDest));
};
